# -*- coding: utf-8 -*-
"""Cópia de ETL/Bovespa.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wK2x8qso7X7bdYu3kbZHPuC0kxsk1NEf

Extrair dados bovespa
"""

import pandas as pd
#Usando as informaçõe da estrutura do arquivo "SeriesHistoricas_Layout", realiazamos extratação dos registrohistoricas por papel-mercado

colspecs = [(2,10),
            (10,12),            
            (12,24),
            (27,39),
            (56,69),
            (69,82),
            (82,95),
            (108,121),
            (152,170),
            (170,188)
            ]

names = ['data_pregao','codbdi','segla_acao','nome_acao','preco_abertura','preco_maximo','preco_menimo','preco_fechamento','qtd_negocios','volume_negocios']           
#Usado skiprows para pular Header
df = pd.read_fwf('/content/drive/MyDrive/ETL Bovespa/COTAHIST_A2021.TXT',colspecs = colspecs, names = names, skiprows = 1)

df

#Transformando alguns campos(data_pregao)

"""Transformação"""

#Filtrando somentes as açoes com cdbdi = 2
df = df[df['codbdi']== 2]
df = df.drop(['codbdi'],1)

df

#ajuste campo de data
df['data_pregao'] =pd.to_datetime(df['data_pregao'], format = '%Y%m%d')
df

#Ajuste dos campos numérios
df['preco_abertura'] =(df['preco_abertura']/100).astype(float)
df['preco_fechamento'] =(df['preco_fechamento']/100).astype(float)
df['preco_maximo'] =(df['preco_maximo']/100).astype(float)
df['preco_menimo'] =(df['preco_menimo']/100).astype(float)
df

df.to_csv("/content/resultado.csv",index=False)